services:
  backend:
    image: ghcr.io/duyp6090/doi_appication:latest
    container_name: backend_carhub
    restart: always
    env_file:
      - .env
    ports:
      - $PORT:$PORT
    networks:
      - backend-network
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      TZ: UTC
    env_file:
      - .env
    ports:
      - $PORT_DB:$PORT_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initDB:/docker-entrypoint-initdb.d
    networks:
      - backend-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend-network

volumes:
  postgres_data:
  redis_data:

networks:
  backend-network:
    driver: bridge
    name: backend-network
